import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  View: {
    backgroundColor: '#fff',
    width: '100%',
    height: '100%',
    paddingTop: 40,
    padding: 20,
    display: 'flex',
    alignItems: 'center'
  },
  ViewBackIcon: {
    padding: 16,
    marginTop: 30,
    width: '100%',
    display: 'flex',
    alignItems: 'flex-start',
  },
  BackIcon: {
    backgroundColor: '#CBD6FF',
    borderRadius: 30,
    padding: 4,
    textAlign: 'center'
  },
  ViewTop: {
    width: '80%',
  },
  Title: {
    color: '#1F41BB',
    textAlign: 'center',
    fontFamily: 'Poppins_700Bold',
    fontSize: 30,
  },
  SubTitle: {
    color: '#000',
    textAlign: 'center',
    fontFamily: 'Poppins_500Medium',
    fontSize: 14,
    fontStyle: 'normal',
    marginTop: 10,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#1F41BB',
  },
  container: { flex: 1, backgroundColor: '#fff', padding: 30, alignItems: 'center' },
  avatar: { width: 100, height: 100, borderRadius: 50, marginBottom: 15 },
  name: { fontSize: 20, fontWeight: '600', textTransform: 'capitalize' },
  subtitle: { fontSize: 14, color: 'gray', marginBottom: 20 },
  inputView: {
    width: '100%',
    gap: 12,
  },
  label: { 
    color: '#262422',
    alignSelf: 'flex-start', 
    fontFamily: 'Poppins_600SemiBold',
    marginTop: 15, 
    fontSize: 14
  },
  input: {
    alignSelf: 'flex-start',
    borderWidth: 2,
    borderColor: '#F1ECEC',
    padding: 12,
    width: '100%',
    borderRadius: 10,
    color: 'gray',
  },
  buttonDocs: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#1F41BB',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  buttonDocsText: { 
    color: '#1F41BB', 
    fontWeight: '600',
    textAlign: 'center',
  },
  buttons: { flexDirection: 'row', justifyContent: 'space-between', gap: 20, marginTop: 100 },
  buttonRecusar: {
    backgroundColor: '#EF5350',
    padding: 15,
    borderRadius: 10,
    width: '45%',
    alignItems: 'center',
    shadowColor: '#FCA9A9',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 10,
  },
  buttonAprovar: {
    backgroundColor: '#4CAF50',
    padding: 15,
    borderRadius: 10,
    width: '45%',
    alignItems: 'center',
    shadowColor: '#B9F8C7',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 10,
  },
  buttonText: { color: '#fff', fontWeight: 'bold' },

  modalBackground: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'center',
  alignItems: 'center',
},
modalContainer: {
  width: '80%',
  backgroundColor: 'white',
  padding: 20,
  borderRadius: 10,
  alignItems: 'center',
  elevation: 5,
},
modalTitle: {
  fontSize: 16,
  fontWeight: 'bold',
  marginBottom: 20,
  textAlign: 'center',
},
modalButtons: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  width: '100%',
},
modalButtonCancel: {
  backgroundColor: '#aaa',
  padding: 10,
  borderRadius: 8,
  width: '45%',
  alignItems: 'center',
},
modalButtonConfirm: {
  backgroundColor: '#EF5350',
  padding: 10,
  borderRadius: 8,
  width: '45%',
  alignItems: 'center',
},
modalInput: {
  width: '100%',
  minHeight: 100,
  borderWidth: 1,
  borderColor: '#ccc',
  borderRadius: 8,
  padding: 10,
  textAlignVertical: 'top',
  color: '#000',
  marginBottom: 20,
},


});