import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  View: {
    backgroundColor: '#1849D6',
    width: '100%',
    height: '100%',
    paddingTop: 40,
    padding: 20,
    display: 'flex',
    alignItems: 'center',
  },
  ViewTop: {
    width: '100%',
    height: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 15,
  },
  TextSucess: {
    color: '#fff',
    fontSize: 32,
    fontFamily: 'Poppins_700Bold',
    textAlign: 'center',
  },
  ViewBottom: {
    width: '100%',
    height: '38%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  ContinueButton: {
    width: 357,
    paddingHorizontal: 20,
    paddingVertical: 15,
    display: 'flex',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginTop: 63,
    shadowColor: '#3B67E9',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  TextButton: {
    color: '#1849D6',
    textAlign: 'center',
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 20,
  },
});